"""add date_formed field to Band model

Revision ID: f47f859426f3
Revises: cbf4f8e80616
Create Date: 2025-10-26 11:05:15.046246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f47f859426f3'
down_revision: Union[str, Sequence[str], None] = 'cbf4f8e80616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('band', sa.Column('date_formed', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('band', 'date_formed')
    # ### end Alembic commands ###
